# 1. HTTP Server - ACME Challenge & Redirect
server {
    listen 80;
    listen [::]:80;
    server_name tamasandor.de www.tamasandor.de; # Replace with your actual domain

    # ACME Challenge endpoint
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}


# 2. HTTPS Server
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name tamasandor.de www.tamasandor.de;

    root /usr/share/nginx/html;
    index index.html;

    # SSL Certificates (Mounted from ./certs)
    ssl_certificate /etc/letsencrypt/live/tamasandor.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tamasandor.de/privkey.pem;

    # Modern SSL Security
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location ^~ /blog-content/ {
        alias /usr/share/nginx/blog-content/;
        expires -1;            # Don't cache so new posts appear instantly
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }


    # Static Assets Caching
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Prevent caching of index.html
    location = /index.html {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # SPA Client-Side Routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
